// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/spot.proto

package spot_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer string `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Input_Value
	//	*Input_Chunk
	Data isInput_Data `protobuf_oneof:"data"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_proto_spot_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (m *Input) GetData() isInput_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Input) GetValue() string {
	if x, ok := x.GetData().(*Input_Value); ok {
		return x.Value
	}
	return ""
}

func (x *Input) GetChunk() []byte {
	if x, ok := x.GetData().(*Input_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isInput_Data interface {
	isInput_Data()
}

type Input_Value struct {
	Value string `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

type Input_Chunk struct {
	Chunk []byte `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"`
}

func (*Input_Value) isInput_Data() {}

func (*Input_Chunk) isInput_Data() {}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Output_Value
	//	*Output_Chunk
	Data isOutput_Data `protobuf_oneof:"data"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_proto_spot_proto_rawDescGZIP(), []int{1}
}

func (m *Output) GetData() isOutput_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Output) GetValue() string {
	if x, ok := x.GetData().(*Output_Value); ok {
		return x.Value
	}
	return ""
}

func (x *Output) GetChunk() []byte {
	if x, ok := x.GetData().(*Output_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isOutput_Data interface {
	isOutput_Data()
}

type Output_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type Output_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*Output_Value) isOutput_Data() {}

func (*Output_Chunk) isOutput_Data() {}

type Layers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers []string `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
}

func (x *Layers) Reset() {
	*x = Layers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layers) ProtoMessage() {}

func (x *Layers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layers.ProtoReflect.Descriptor instead.
func (*Layers) Descriptor() ([]byte, []int) {
	return file_proto_spot_proto_rawDescGZIP(), []int{2}
}

func (x *Layers) GetLayers() []string {
	if x != nil {
		return x.Layers
	}
	return nil
}

var File_proto_spot_proto protoreflect.FileDescriptor

var file_proto_spot_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x40, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x20, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x32, 0x9d, 0x01, 0x0a, 0x04, 0x53, 0x70, 0x6f, 0x74, 0x12, 0x35, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x2e, 0x73, 0x70,
	0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0f, 0x2e, 0x73, 0x70,
	0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x35, 0x0a, 0x10,
	0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x0e, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x0f, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x5f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spot_proto_rawDescOnce sync.Once
	file_proto_spot_proto_rawDescData = file_proto_spot_proto_rawDesc
)

func file_proto_spot_proto_rawDescGZIP() []byte {
	file_proto_spot_proto_rawDescOnce.Do(func() {
		file_proto_spot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spot_proto_rawDescData)
	})
	return file_proto_spot_proto_rawDescData
}

var file_proto_spot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_spot_proto_goTypes = []interface{}{
	(*Input)(nil),         // 0: spot.v1.Input
	(*Output)(nil),        // 1: spot.v1.Output
	(*Layers)(nil),        // 2: spot.v1.Layers
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_proto_spot_proto_depIdxs = []int32{
	3, // 0: spot.v1.Spot.ListLayers:input_type -> google.protobuf.Empty
	0, // 1: spot.v1.Spot.Call:input_type -> spot.v1.Input
	0, // 2: spot.v1.Spot.CallStreamOutput:input_type -> spot.v1.Input
	2, // 3: spot.v1.Spot.ListLayers:output_type -> spot.v1.Layers
	1, // 4: spot.v1.Spot.Call:output_type -> spot.v1.Output
	1, // 5: spot.v1.Spot.CallStreamOutput:output_type -> spot.v1.Output
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spot_proto_init() }
func file_proto_spot_proto_init() {
	if File_proto_spot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_spot_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Input_Value)(nil),
		(*Input_Chunk)(nil),
	}
	file_proto_spot_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Output_Value)(nil),
		(*Output_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spot_proto_goTypes,
		DependencyIndexes: file_proto_spot_proto_depIdxs,
		MessageInfos:      file_proto_spot_proto_msgTypes,
	}.Build()
	File_proto_spot_proto = out.File
	file_proto_spot_proto_rawDesc = nil
	file_proto_spot_proto_goTypes = nil
	file_proto_spot_proto_depIdxs = nil
}
